agent:
    ros__parameters:
        device: 'cpu'

#gui:
#    ros__parameters:

supervisor:
    ros__parameters:
        frequency: 2.0
        max_episode_length: 75

#joystick:
#    ros__parameters:
