agent:
    ros__parameters:
        device: 'cpu'

gui:
    ros__parameters:
        max_linear_velocity: 0.1
        max_angular_velocity: 0.25

supervisor:
    ros__parameters:
        frequency: 2.0
        max_episode_length: 100
        max_linear_velocity: 0.1
        max_angular_velocity: 0.25

joystick:
    ros__parameters:
        max_linear_velocity: 0.1
        max_angular_velocity: 0.25
