supervisor:
    ros__parameters:
        frequency: 0.6
        max_linear_velocity: 0.05
        max_angular_velocity: 0.125

joystick:
    ros__parameters:
        max_linear_velocity: 0.05
        max_angular_velocity: 0.125