start_training__RL:
    training_type: 'RL'
    algorithm_name: 'TD3_SLRL'
    save_every: 10
    max_epochs: 1000
    additional_algorithm_kwargs:
        run_name: 'tmp'
        run_id: 101
        checkpoint_every: 10
        device: 'cuda:0'
        discount: 0.98
        tau: 0.05
        noise: 0.1
        run_decay: -0.005
        logger_name: 'WandbLogger'
