wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.8.10
    start_time: 1640076355
    t:
      1:
      - 1
      3:
      - 13
      - 14
      - 16
      4: 3.8.10
      5: 0.12.7
      8:
      - 2
      - 5
actor_optimizer:
  desc: null
  value:
    optimizer_kwargs:
      lr: 0.001
      weight_decay: 0.001
    optimizer_name: Adam
actor_update_period:
  desc: null
  value: 2
critic_optimizer:
  desc: null
  value:
    optimizer_kwargs:
      lr: 0.001
      weight_decay: 0.001
    optimizer_name: Adam
discount:
  desc: null
  value: 0.95
noise:
  desc: null
  value: 0.3
tau:
  desc: null
  value: 0.2
